import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(req) {
     try {
          const data = await req.json();
          const { name, email, subject, phone, message } = data;

          // Basic Validation check
          if (!name || !email || !message) {
               return NextResponse.json({ message: "Missing required fields" }, { status: 400 });
          }

          const transporter = nodemailer.createTransport({
               host: process.env.MAIL_HOST,
               port: Number(process.env.MAIL_PORT),
               secure: process.env.MAIL_SECURE === "true",
               auth: {
                    user: process.env.MAIL_USER,
                    pass: process.env.MAIL_PASS,
               },
          });

          const mailOptions = {
               from: `"Portfolio" <${process.env.MAIL_USER}>`,
               to: process.env.MAIL_USER,
               replyTo: email,
               subject: `[CONTACT_FORM] ${subject}`,
               html: `
        <!DOCTYPE html>
        <html>
          <head>
            <style>
              .container { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #1a1a1a; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; }
              .header { background-color: #c778dd; color: #ffffff; padding: 30px; text-align: center; }
              .content { padding: 30px; background-color: #ffffff; }
              .field-box { margin-bottom: 25px; border-bottom: 1px solid #f1f5f9; pb: 15px; }
              .label { color: #64748b; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; font-weight: bold; margin-bottom: 5px; }
              .value { color: #1e293b; font-size: 16px; margin: 0; }
              .message-box { background-color: #f8fafc; border-left: 4px solid #c778dd; padding: 20px; border-radius: 4px; font-style: italic; color: #334155; }
              .footer { background-color: #f1f5f9; padding: 20px; text-align: center; font-size: 12px; color: #94a3b8; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1 style="margin:0; font-size: 24px; letter-spacing: 2px;">NEW INQUIRY</h1>
              </div>
              <div class="content">
                <div class="field-box">
                  <p class="label">User_Identify</p>
                  <p class="value"><strong>${name}</strong></p>
                </div>
                <div class="field-box">
                  <p class="label">Contact_Point</p>
                  <p class="value">${email} ${phone ? `| ${phone}` : ''}</p>
                </div>
                <div class="field-box">
                  <p class="label">Subject_Line</p>
                  <p class="value">${subject}</p>
                </div>
                <div class="field-box" style="border:none;">
                  <p class="label">Payload_Message</p>
                  <div class="message-box">"${message}"</div>
                </div>
              </div>
              <div class="footer">
                <p>Generated by Abhijet Portfolio System • ${new Date().toLocaleString()}</p>
                <p>This is an encrypted transmission. Handle with care.</p>
              </div>
            </div>
          </body>
        </html>
      `,
          };

          await transporter.sendMail(mailOptions);

          return NextResponse.json({ message: "Data transmitted successfully" }, { status: 200 });

     } catch (error) {
          console.error("Critical System Error:", error);
          return NextResponse.json({ message: "Transmission failed" }, { status: 500 });
     }
}